# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: udpapi
    build: .
    # command: udpapi run -h 0.0.0.0
    command: python udpapi/manage.py run -h 0.0.0.0
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/udpapi.db
    volumes:
      - ./udpapi:/code/udpapi
      - ./db/:/db/
    ports:
      - "5000:5000"
